name: Electron Build and Release

on:
  push:
    branches:
      - 'main'
      - 'master'
      - 'development'
    paths-ignore:
      - '**.md'
      - '**.yml'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install Setuptools for Python (macOS only)
        if: matrix.os == 'macos-latest'
        run: pip3 install setuptools --break-system-packages

      - name: Install dependencies
        run: cd electron && pnpm install

      - name: Build and Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd electron
          npm run publish

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ matrix.os }}
          path: electron/dist/**
          if-no-files-found: error
